### ISSUE TITLE
Plants disappear on fertilized soil

### ISSUE THREAD

**Issue by Polarite** [LordDeatHunter/Croptosis#13] opened 2022-03-27 18:40 UTC
for some reason after I plant anything on fertilized soil it disappears instantly
fabric 1.18.2

**Comment by LordDeatHunter** [comment] 2022-05-15 18:40
Modded or vanilla crops? Is this on singleplayer or multiplayer? If multiplayer, is it installed on both server & client?

**Comment by LordDeatHunter** [comment] 2022-06-07 21:41
Closing the issue as I cannot reproduce, if you run into it again, feel free to re-open with more info.

**Closed as completed by LordDeatHunter** 2022-06-07 21:41 UTC
