### ISSUE TITLE
Sandwichable and ValleyCraft crops not compatible.

### ISSUE THREAD

**Issue by nephatrine** [LordDeatHunter/Croptosis#12] opened 2022-02-18 23:18 UTC
The crops from these two mods are not able to be planted on croptosis fertilized soil. I am using `wraith-croptosis-1.4.2` in 1.18.1.

**Comment by LordDeatHunter** [comment] 2022-05-15 18:44
Cannot replicate with latest versions.
![image](https://user-images.githubusercontent.com/26803198/168488846-240cb3e3-5096-4fab-aea6-1b4cb464f01e.png)

**Comment by LordDeatHunter** [comment] 2022-06-07 21:41
Closing the issue as I cannot reproduce, if you run into it again, feel free to re-open with more info.

**Closed as completed by LordDeatHunter** 2022-06-07 21:41 UTC
